### ISSUE TITLE
Show absolute _and_ relative time

### ISSUE THREAD

**Issue by dancrew32** [Nextdoor/conductor#35]
When searching backwards to find a train that deployed at a very specific time, it can be frustrating to only see relative time in these parts of the UI:

https://github.com/Nextdoor/conductor/blob/53ecc3ee7b7ad3a55b96982549c3374a315440a9/frontend/src/components/Details.jsx#L35-L36

https://github.com/Nextdoor/conductor/blob/dafa8aaa743cbec61fee0a9f823fd3f819cfeee2/frontend/src/components/Phases.jsx#L175

https://github.com/Nextdoor/conductor/blob/92d83a355efadc443e0cf01f7493c04454adffde/frontend/src/components/Summary.jsx#L124

Proposing rendering the absolute iso format datetime with relative time in parenthesis.

**Comment by davidkern** [comment]
Seems like a good idea...  feel free to submit a PR!

**Comment by eshaverma** [comment]
I think should just put a global value somewhere in the cards called train launched at XX:XX PST.
and the rest can stay as relative values as it is.

**Comment by eshaverma** [comment]
closing issue unless anyone objects
