### ISSUE TITLE
Please remove me from CODEOWNERS

### ISSUE THREAD

**Issue by davidkern** [Nextdoor/conductor#77]
Conductor is asking me to do reviews.  (but I don't have a merge button, so that's good!) :-D

Please remove @davidkern from CODEOWNERS.  Thank you!

**Comment by davidkern** [comment]
cc @eshaverma

**Comment by masterginger** [comment]
LOL, I thought I was delusional :)

**Comment by davidkern** [comment]
I approve of updating your dependencies!

**Comment by davidkern** [comment]
Thanks!
